# Generated by Django 3.1 on 2020-08-23 20:41

from django.db import migrations, models
import vending_machine_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine_api', '0003_auto_20200823_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coin',
            name='name',
        ),
        migrations.AddField(
            model_name='coin',
            name='unit',
            field=models.PositiveIntegerField(default=vending_machine_api.models.CoinEnum['PENCE_1'], verbose_name='Coin Type/Unit'),
        ),
        migrations.AlterField(
            model_name='coin',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Numeber of Coins'),
        ),
    ]
