# Generated by Django 3.1 on 2020-08-26 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vending_machine_api', '0009_auto_20200824_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CoinWallet',
            new_name='CoinRegister',
        ),
    ]
